version: "3"
services:

  app:
    build:
      context: .
      # dockerfile: ./Dockerfile
      target: dev
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: .
        # source: ./cmd/app
        target: /app/
    # user: root
    # entrypoint: tail -f /dev/null

  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    # networks:
    #   - consumer