services:
  app:
    build:
      context: .
      # dockerfile: ./Dockerfile
      target: dev
    ports:
      - 8082:8080
    volumes:
      # - type: bind
      #   source: .
      #   # source: ./cmd/app
      #   target: /app/
      - .:/app/
    # user: root
    # entrypoint: tail -f /dev/null
    environment:
      - DBPASS=root
      - DBUSER=root
      - DBHOST=mysql
      - OTEL_RESOURCE_ATTRIBUTES=service.name=app,service.version=0.1.0
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      # - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
      - KEYCLOAK_CLIENT_ID=appclient
      - KEYCLOAK_CLIENT_SECRET=5gplu6KShV8gN5vOlEqGA0LfFydBeLwV
      - KEYCLOAK_REDIRECT_URL=http://localhost:8082/api/v1/auth2/callback
      - KEYCLOAK_PUBLIC_URL=http://mykeycloak:8080/realms/app
      - KEYCLOAK_ISSUER_URL=http://mykeycloak:8080/realms/app
      
      
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    restart: always
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
    

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    # networks:
    #   - consumer
    depends_on:
      - mysql

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.100.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317
      - 9091:9090

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - 16686:16686

  mykeycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - KC_HOSTNAME=localhost
      - KC_METRICS_ENABLED=false
    # command: start --hostname-port=8082 --optimized
    command: start-dev
