services:
  app:
    build:
      context: .
      # dockerfile: ./Dockerfile
      target: dev2
    ports:
      - 8080:8080
    volumes:
      # - type: bind
      #   source: .
      #   # source: ./cmd/app
      #   target: /app/
      - .:/app/
    # user: root
    # entrypoint: tail -f /dev/null
    environment:
      - DBPASS=root
      - DBUSER=root
      - DBHOST=mysql
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
      
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    restart: always
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
    

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    # networks:
    #   - consumer
    depends_on:
      - mysql

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.100.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - 16686:16686      