CREATE TABLE IF NOT EXISTS `cats` (
    `id` SERIAL PRIMARY KEY ,
    `name` VARCHAR(100) NOT NULL ,
    `age` TINYINT NOT NULL ,
    `breed` VARCHAR(100) NOT NULL,    
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);