basePath: /api/v1
definitions:
  controller.JSONResult:
    properties:
      data:
        $ref: '#/definitions/services.Cat'
      message:
        type: string
    type: object
  controller.JSONResultList:
    properties:
      data:
        items:
          $ref: '#/definitions/services.Cat'
        type: array
      message:
        type: string
    type: object
  services.Cat:
    properties:
      age:
        type: integer
      breed:
        type: string
      name:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /cats:
    get:
      consumes:
      - application/json
      description: Get all cats
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JSONResultList'
      summary: Get all cats
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: Insert a Cat
      parameters:
      - description: cat
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.Cat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JSONResult'
      summary: Create Cat
      tags:
      - accounts
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
